server:
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      strategy: com.baomidou.dynamic.datasource.strategy.LoadBalanceDynamicDataSourceStrategy
      #hikari数据库连接池
      hikari:
        pool-name: Retail_HikariCP
        idle-timeout: 60000 #空闲连接存活最大时间，默认600000（10分钟）
        max-lifetime: 600000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
        connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
        connection-test-query: SELECT 1
        connection-init-sql: SELECT 1
        leak-detection-threshold: 5000
        validation-timeout: 60000
        max-pool-size: 60
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/user?autoReconnect=true&serverTimezone=Asia/Shanghai
          username: 'root'
          password: '123456'
        slave_1:
          url: jdbc:mysql://127.0.0.1:3306/user1?autoReconnect=true&serverTimezone=Asia/Shanghai
          username: 'root'
          password: '123456'
        slave_2:
          url: jdbc:mysql://127.0.0.1:3306/user2?autoReconnect=true&serverTimezone=Asia/Shanghai
          username: 'root'
          password: '123456'

  servlet:
    multipart:
      enabled: true
      #单文件大小
      max-file-size: 5MB
      #总上传数据大小
      max-request-size: 10MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss.SSS
    time-zone: GMT+8
    defaultPropertyInclusion: non_null   #非空属性才序列化
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false #未定义的key不序列化

mybatis-plus:
  # Mapper.xml 文件位置 Maven 多模块项目的扫描路径需以 classpath*: 开头
  mapperLocations: classpath*:mapper/*Mapper.xml
  configuration: # MyBatis 原生支持的配置
    # 是否开启自动驼峰命名规则（camel case）映射
    mapUnderscoreToCamelCase: true
    #缓存开启
    cache-enabled: true
  global-config: # 全局策略配置
    # 是否控制台 print mybatis-plus 的 LOGO
    banner: false
    db-config:
      # id类型
      id-type: auto
      # 表名是否使用下划线命名，默认数据库表使用下划线命名
      table-underline: true
#      logic-delete-field: deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
#      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

